sudo: required
services:
  - docker

before_install:
  - docker build -t maiqubal/docker-prodbuild -f Dockerfile.dev .

script:
  - docker run -e CI=true maiqubal/docker-prodbuild npm run test